apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yp48h25ka-nodejs 
  janus-idp.io/tekton: yp48h25ka-nodejs
  backstage.io/kubernetes-id: yp48h25ka-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yp48h25ka-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml